name: Hello World

on:
  push:
   branches: [ main ]
  pull_request:
    branches: [ main ]
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "tabishmehdi" --password-stdin
        docker image build -t tabishmehdi/web-app-github-action:latest .
        docker push tabishmehdi/web-app-github-action:latest